README.md
bundles.go
docs/sbctl.8.txt

Signed-off-by: George Rawlinson <george@rawlinson.net.nz>

Fix some minor typos in documentation & CLI output

---

README.md

Unfamiliar with this project but hopefully got that spelling correct.

Fix sbsigntools typo in README

---

Makefile
README.md
cmd/sbctl/main.go
go.sum
log.go

Based on the comments in #30, this PR adds the staticcheck linter and fixes errors found during analysis.

Add staticcheck linter

---

.github/workflows/ci.yaml

Arch and Void containers, initially.

Add CI via GitHub actions.

---

chattr.go

Keep FS_* constants which aren't listed in the package, and leave
SetAttr there, even though it's currently not used.

Use x/sys/unix for ioctl instead of rolling our own.

---

bundles.go
database.go
keys.go
sbctl.go
util.go

Deprecated in GO 1.16
Closes #55

Remove ioutil

---

docs/sbctl.8.txt

I've added some details which I think will be appreciated by future adopters.

Extend the documentation a bit

---

sbctl.go

Now checks /efi,/boot and /boot/efi for gpt partition table,
vfat filesystem and ESP partition GUID.
Closes #44

Improved GetEsp function.

---

keys.go

fix: restrict key file permissions

---

bundles.go

Noticed this issue when using `sbctl` to build a bundle on aarch64.
I added these three architectures because they're the ones for which systemd ships a stub; no more, no less.

Remove hardcoded architecture in filename

---

.github/workflows/ci.yaml
Makefile
cmd/sbctl/enroll-keys.go

Fixes CI currently failing (previously just arch, now also on void).
I recommend reviewing commits individually for the whole PR to make sense.

Go needs `git` installed

---

contrib/kernel-install/91-sbctl.install

Add support for the uki layout

---

bundles.go

I noticed UKI generation in sbctl uses hardcoded values even though the ArchWiki advises against it, and mkinitcpio was updated to fix this.
The logic is based on the ArchWiki and mkinitcpio implementations, but uses the `debug/pe` package to calculate the VMA/offset, instead of objdump+awk.
https://wiki.archlinux.org/title/Unified_kernel_image#Manually
https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/merge_requests/182
https://pkg.go.dev/debug/pe

Fix arbitrary sizes in UKI generation

---

dmi/dmi_test.go

Oops, just checked the merge and noticed I somehow missed these 3.

dmi: Test all used DMI fields

---

README.md

Referring to https://github.com/Foxboron/sbctl/issues/167#issuecomment-1477121243

Add packages section to README

---

README.md

Add asciidoc dependency to README

---

cmd/sbctl/enroll-keys.go

Allow keys to be partially enrolled via --partial flag.

feat(enroll-keys): add partial enrollment of keys

---

cmd/sbctl/import-keys.go

fix: Create dest directory when importing keys

---

.github/workflows/ci.yaml

See: https://github.com/Foxboron/sbctl/actions/runs/8008805592/job/21876043359#step:3:7

ci.yaml: use github container registry 

---

cmd/sbctl/debug.go
config/config.go

It's to help us debug issues with sbctl and UEFI things.
Fixes: https://github.com/Foxboron/sbctl/issues/287

Implment sbctl debug command

---

cmd/sbctl/enroll-keys.go

enroll-keys: if --export, add CWD to RWDirs

---

.github/workflows/build.yml

See: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#supported-characters

build.yml: download artifacts  using a wildcard

---

cmd/sbctl/verify.go

Implement rather simple but functional JSON output mode for verify.

Verified JSON support
