keys.go
sbctl.go

SignFile was performing the wrong verification to see if it could skip signing a file, and VerifyESP was printing the wrong error message when the output file couldn't be found.

Fix SignFile and VerifyESP

---

cmd/sbctl/main.go

Errors out if trying to remove-file or remove-bundle a file that isn't
in the database. Needs a better log message format.
Fixes #17

main: verify if files exist before removing them.

---

cmd/sbctl/main.go
sbctl.go

...and sign them by default when generated in a `sign-all` call.
Fixes #26 .
Copy-paste of what I said in the issue:
I spotted a [lonely, unused flag](https://github.com/Foxboron/sbctl/blame/fda4f2c1efd801cd04fb52923afcdb34baa42369/cmd/sbctl/main.go#L232) called `sign` in `generateBundlesCmd()` and took the liberty to give it some purpose and make it actually sign the bundles after creation. ;)
This presents us with an easy solution:
Thanks to the `sign` flag, the bundles are only signed optionally on creation, which is good. We could of course introduce another flag, however in the situation where someone calls `sign-all --generate`, I think it's fair to assume that he/she also wants the generated bundles to be signed, considering the very name of that command. So whenever we call …

Implement optional signing of bundles on creation

---

.github/workflows/ci.yaml

Set GOBIN during `make deps` so staticcheck is installed directly in a
directory already in PATH.

Fix lint step in CI.

---

bundles.go
cmd/sbctl/main.go
database.go
go.mod
go.sum
keys.go
log.go
sbctl.go
util.go

I'm not sure I need to check the array length, because I don't think it enters the function if there isn't any command at all. But I didn't want to risk it.
Could be changed to `strings.Fields(c.CommandPath())[1]` directly.

main: help subcommand should work without root.

---

keys.go

keys: sbkeysync can have "Permissiond denide" errors

---

chattr.go
sbctl.go
util.go

This allows us to give a sensible error for `enroll-keys` if the files
are set as immutable.
$ sbctl enroll-keys
==> ERROR: File is immutable: /sys/firmware/efi/efivars/PK-8be4df61-93ca-11d2-aa0d-00e098032b8c
==> ERROR: File is immutable: /sys/firmware/efi/efivars/KEK-8be4df61-93ca-11d2-aa0d-00e098032b8c
==> ERROR: File is immutable: /sys/firmware/efi/efivars/db-d719b2cb-3d3a-4596-a3bc-dad00e67656f
==> ERROR: You need to chattr -i files in efivarfs

sbctl: Check for immutable files before sbkeysync

---

sbctl.go

We can always stat files, but it's enough to figure out if we can
actually check the signature. Instead we try to open the file.
This patch also moves us to the new errors package
$ sbctl verify
==> Verifying file database and EFI images in /efi...
-> WARNING: /boot/EFI/BOOT/BOOTX64.EFI is not signed
-> WARNING: /boot/EFI/arch/fwupdx64.efi is not signed
-> WARNING: /boot/EFI/systemd/systemd-bootx64.efi is not signed
-> ERROR: /tmp/vmlinuz-linux does not exist
-> ERROR: /tmp/vmlinuz-linuz-test permission denied. Can't read file
Fixes #46

sbctl: Check for persmission denied. Use errors package

---

bundles.go
cmd/sbctl/main.go

Should probably try include some documentation to this, but this changes
the default from /proc/cmdline to /etc/kernel/cmdline.
This is partially a standard and a bit more flexible for everyday use
for most people.
https://www.freedesktop.org/software/systemd/man/kernel-install.html
Fixes #39

sbctl/bundle: Change default cmdline to /etc/kernel/cmdline

---

contrib/pacman/ZZ-sbctl.hook

This should cover systemd and fwupd alike
Fixes #51

sbctl.hook: Renamed to be ordered last, added more paths

---

bundles.go
keys.go

Second commit changes the place of `.splash` argument to be last instead of in the middle but I dont' believe that will change the result. I through the man page of `objcopy` and there is no mention of order at `--add-section` or `--change-section-vma`.
Closes #60

Use arrays of arguments instead of spliting by white space 

---

docs/sbctl.8.txt

The default cmdline is `/etc/kernel/cmdline`, but the man page said `/proc/cmdline`.

Update man entry for default cmdline

---

cmd/sbctl/verify.go

Was leading to double newlines in the "sbctl verify" output.
Signed-off-by: Érico Nogueira <erico.erc@gmail.com>

sbctl/verify: remove accidental newline

---

logging/logging.go

Use simple unicode symbols in logging, instead of (possibly) emojis.
These two symbols should exist in most monospace fonts, so they can be shown with correct colors, without falling back to emojis, in most cases. They are also what systemd uses in their yes/no style output.

logging: use simple unicode symbols

---

bundles.go
cmd/sbctl/bundle.go
cmd/sbctl/list-bundles.go
cmd/sbctl/verify.go
sbctl.go

Attempt to trigger automounts to find the ESP
The ESP may be an automount partition, so try touching a file in each
candidate location so as to trigger an automounts.
This is the same way systemd attempts to find it:
https://github.com/systemd/systemd/blob/f565b86/src/shared/bootspec.c#L1014-L1018
I've also changed the function to return an error if no ESP is found.
The previous behaviour (an empty string) just results in a crash later
on.
When no ESP is found, the `bundle` command will have no default for the
`esp` flag. Passing an empty string to it as a default results in no
value being show in the output of `--help`.
This seemed like the most reasonable compromise instead of panicking.
Fixes #78

Attempt to trigger automounts to find the ESP

---

util.go

CheckMSDos attempts to read the first two bytes of a file to determine
if it is an MS-DOS executable. If a file (for whatever reason) is shorter,
attempting to read this will result in an `io.EOF` error.
The error can be safely ignore because such an error indicates that the file
could be read successfully, it just doesn't contain enough bytes.
Possibly resolves #96

Ignore EOF errors in CheckMSDos

---

cmd/sbctl/sign-all.go
docs/sbctl.8.txt

#113 fixed this same thing for `sign.go`, hopefully this is the last one :)

Fix minor typo

---

cmd/sbctl/import-keys.go

Have `sbctl import-keys` read from correct private key files.

read key from private key file

---

cmd/sbctl/enroll-keys.go

Fail `enroll-keys` if any key file does not exist

---

cmd/sbctl/list-bundles.go
cmd/sbctl/list-files.go
cmd/sbctl/remove-bundle.go
cmd/sbctl/remove-file.go
docs/sbctl.8.txt

Add convenient aliases for some sub-commands.
Aliases added:
- `list-bundles`
- `ls-bundles`
- `list-files`
- `ls-files`
- `ls`
- `remove-bundle`
- `rm-bundle`
- `remove-file`
- `rm-file`
- `rm`
If you don't agree with the `ls` and `rm` aliases I can remove them.

Add convenient aliases for some sub-commands

---

.gitignore
bundles.go

Generating a new bundle with an unmounted ESP would crash trying to find
one, even if one was explicitly specified.
This was due to Bundle instances always being created with a discovered
ESP path. However, this path is always overwritten based on the value
provided by the user, meaning that this default is unused and always
overwritten.
This changes NewBundle to simply use an empty ESP if finding one fails.
This has no impact on `sbctl` itself. This change COULD impact
applications using this codes as a library, but this only affects code
that previously panicked.
Fixes: https://github.com/Foxboron/sbctl/issues/132

Fix crash when ESP is not mounted

---

docs/sbctl.8.txt

`cmd/sbctl/bundle.go` sources different default paths for initramfs and kernel image location than what the manpage states `sbctl bundle` will source.

update manpage to reflect defaults in bundle.go

---

docs/sbctl.8.txt

The previous instructions were completely wrong: To entroll custom keys
the firmware has to be in setup mode. By enrolling our own keys we enter
user mode! Also, setup mode is automatically entered on PK enrollment,
requiring no further user interaction in the firmware.

sbctl.8: Provide more precide setup mode instructions

---

docs/sbctl.8.txt
docs/workflow-example.md

Hey Morten,
thanks for sbctl, once again. 
Reading the [usage guide](https://man.archlinux.org/man/sbctl.8#USAGE), I noticed some typos, just to find most of them fixed in master already. 
However, I ran 
```languagetool -d WHITESPACE_RULE,COMMA_PARENTHESIS_WHITESPACE,UPPERCASE_SENTENCE_START,REP_PASSIVE_VOICE docs/{sbctl.8.txt}``` 
just to check up on the docs and implemented the suggestions.
Hope this PR is appreciated.
Best,
Patrik
Signed-off-by: Patrik Tesarik <mail@patrik-tesarik.de>

Fix typos and some improve grammar a bit

---

contrib/pacman/ZZ-sbctl.hook

archlinux install out-of-tree dirvers such as nvidia under `usr/lib/modules/*/extramodules/*`. Modifying out-of-tree dirvers could trigger mkinitcpio.

pacman: Add 'extramodules' target to hook

---

contrib/kernel-install/91-sbctl.install

In POSIX sh == doesn't really exist; shellcheck warns about this.

Fix POSIX sh comparison

---

cmd/sbctl/status.go

Do not hide the "vendor keys" line if there are no vendor keys; instead indicate explicitly that no vendor keys are present.
I found this behaviour a bit confusing when setting up secure boot; it took me a while to realize that the MS keys were indeed not installed, because a flag in the firmware UI suggested otherwise, and I assumed sbctl was misbehaving.
Given that the absence of vendor keys can cause a lot of trouble depending on the hardware, I also think it's better to indicate their absence explicitly.

Always include vendor keys in status output

---

cmd/sbctl/status.go
cmd/sbctl/status_test.go
dmi/dmi.go
dmi/dmi_test.go
quirks/fq0001.go
quirks/quirks.go

Related: https://github.com/Foxboron/sbctl/issues/181
Just a rough idea, would like to hear your input.
```
{
"installed": true,
"guid": "6e2b1be3-6ecf-41e6-a59b-a30efdfa85ba",
"setup_mode": false,
"secure_boot": true,
"vendors": [],
"firmware_quirks": [
{
"id": "FQ0001",
"name": "MSI defaults to executing on policy violation",
"link": "https://github.com/Foxboron/sbctl/wiki/FQ0001",
"severity": "CRITICAL"
}
]
}
```

status: Warn about firmware quirks

---

cmd/sbctl/main.go

Before (bash):
Before (zsh):
---
After (bash):
After (zsh):

Add trailing newline to JSON output

---

certs/certs.go
certs/certs_test.go
cmd/sbctl/enroll-keys.go
docs/sbctl.8.txt

Allow enrolling custom db and KEK certs

---

cmd/sbctl/enroll-keys.go
cmd/sbctl/rotate-keys.go
docs/sbctl.8.txt
go.mod
go.sum
keys.go

Export the keys we intend to enroll as .auth or .esl files

enroll-keys: implement --export

---

certs/builtin.go
cmd/sbctl/enroll-keys.go
cmd/sbctl/status.go
docs/sbctl.8.txt

Supersedes https://github.com/Foxboron/sbctl/pull/147

Add support for loading certificates from dbDefault

---

cmd/sbctl/enroll-keys.go

Followup to #236. This adds support for custom `dbx` databases.
I also added the microsoft one for completenes, but didn't add the current dbx, since that's maybe not the best idea and this should be fetched at runtime rather than be compiled in.
I tested the enrollment of `dbx` with the `--custom` argument on a qemu virtual machine.

Add support for OEM dbx enrollment

---

cmd/sbctl/enroll-keys.go
cmd/sbctl/reset.go
docs/sbctl.8.txt

Added one more flags to enroll-keys and reset respectively: 
Enroll-keys: Append the key to be enrolled to the existing db
Reset: Only remove a specific certs by providing a flag with their paths
I am hesitant to add more flags to the enroll-keys cmd but they do seem useful to me

Add append option

---

bundles.go

It could be provided on the command line

fix: don't immediately fail if we can't find default EFI stub

---

docs/sbctl.8.txt

The support was introduced in dae25b8 without documentation, since dbx was not mentioned at all in the manpage/news at that point in time.

Update documentation for custom dbx

---

keys.go

fixes https://github.com/Foxboron/sbctl/issues/102
been testing this for a while on my thinkpad t460s

keys.go: drop the keyUsage bitfield

---

cmd/sbctl/create-keys.go
docs/sbctl.8.txt

To resolve https://github.com/Foxboron/sbctl/issues/258
This allows the end-user to specify an `export` path. Not entirely sure what the GUID is useful for, tbh, but since I didn't have a `/usr/share/secureboot/` directory, I was still having trouble running this command. I added the ability to specify the `database-path` too.

`create-keys` allows for specifying an export directory

---

tests/utils/certs.go

drop keyusage bitfield from another location, as pointed out in https://github.com/Foxboron/sbctl/pull/255

tests/utils/certs.go: drop keyUsage bitfield

---

cmd/sbctl/create-keys.go

I'm not sure how ```sbctl create``` ever worked with the default paths--- the var {} block initially sets exportPath/databasePath to the default values from the sbctl module, but then pflag.StringVarP() overwrote them with empty string passed in as the ```value``` parameter. From https://github.com/spf13/pflag/blob/master/string.go it looks like that has been the behavior for a long time.
Fixed by passing the values from sbctl as the initialization value in StringVarP().

BUGFIX: f.StringVarP() was clearing the exportPath/databasePath strings

---

cmd/sbctl/enroll-keys.go

Fixes https://github.com/Foxboron/sbctl/issues/264
Tested on my local machine.

Ignore Setup mode and immutable variables for export

---

contrib/mkinitcpio/sbctl
contrib/pacman/ZZ-sbctl.hook

Initrd is rebuilt when a DKMS module or firmware package is installed or updated as of these commits to mkinitcpio: https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/commit/aff81712789b9f2c1664fe1cfb5c1ecdbc5c993b https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/commit/3576b03d29420ccd1913eaa18c7f8950e7de3103
Without this change, images created by mkinitcpio will not be automatically signed for secure boot in the events mentioned above.

Ensure file signing hook is run when initrd is rebuilt

---

contrib/kernel-install/91-sbctl.install

It's expected that signing doesn't work without having previously generated keys, so don't try to sign when keys don't exist.
Closes: https://github.com/Foxboron/sbctl/issues/187
Signed-off-by: John Helmert III <ajak@gentoo.org>

91-sbctl.install: don't sign without signing keys

---

README.md

This package was originally part of [`secure-boot`](https://copr.fedorainfracloud.org/coprs/chenxiaolong/secure-boot/) in which the maintainer mentioned:
> [2023-11-12 Update]: This repo is deprecated because I have switched to using systemd-ukify for generating UKIs. Because sbctl is very useful on its own, **I will continue to package it in a [separate repo](https://copr.fedorainfracloud.org/coprs/chenxiaolong/sbctl/). Folks who currently use this repo should expect things to continue to work, though no further updates will be provided and repos for Fedora 40+ will not be created.**
I asked the maintainer if he'd mind if we added this to the official readme via email. Reply was:
> Sure, I don't mind at all. I actively use sbctl on all my machines, so I intend to keep maintaining the …

Mention COPR package

---

README.md

Since 2023-11-21, openSUSE has shipped sbctl as part of the main repos.
See: [OBS request](https://build.opensuse.org/request/show/1127877)

Add openSUSE to Installation in README

---

cmd/sbctl/sign-all.go

I went ahead and gave it a try
fixes #265

sign-all don't stop signing if one file does not exist anymore

---

contrib/mkinitcpio/sbctl

See #284 for details on the problem.
This PR updates the mkinitcpio post hook to only sign the kernel/UKI which is currently being built instead of all the files in the sbctl database.
References:
- https://man.archlinux.org/man/mkinitcpio.8#ABOUT_POST_HOOKS
- https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#Signing_the_kernel_with_a_mkinitcpio_post_hook
- https://wiki.archlinux.org/title/Unified_kernel_image#Signing_the_UKIs_for_Secure_Boot
Fixes #284

Update the mkinitcpio post hook to only sign the kernel/UKI which is currently being built instead of all the files in the sbctl database

---

contrib/kernel-install/91-sbctl.install

This fixes a problem on fedora.
If this check is not done, removing a kernel will fail and the rpmdb will become corrupt, showing multiple entries. (use: "rpm -e --allmatches" to remove them)
I bet this hack is imperfect, but it sure is a step in the right direction.

only remove entries if they are there

---

cmd/sbctl/list-enrolled-keys.go

to list certificates that are already enrolled on the current system
Background:
In the [Kairos project](https://github.com/kairos-io/kairos/) we need a simple way for our users to enroll custom keys to the firmware. We also need to help them [revoke certain keys](https://github.com/kairos-io/kairos/issues/2429) later. In general, we need a tool that allows them to manage the enrolled keys (list, add, delete).
It [was suggested that sbctl](https://github.com/kairos-io/kairos/issues/2486#issuecomment-2066073266) could satisfy these (or some of these) requirements. This is a first PR to try this option.
-------
I tried to follow the naming conventions of the other commands to stay consistent but we could discuss a different way to structure this new command to allow us to later add …

Add list-enrolled-keys command

---

docs/sbctl.8.txt

The text in the usage section did not mention that some firmware might need Microsoft certificates as well, so I copied pasted it from line 48.
I noticed [on a Reddit comment](https://reddit.com/r/archlinux/comments/uwytxm/bios_brick_after_using_sbctl/i9wvbhp/?context=3) though that there's a warning if option ROM is detected, so this warning might be unnecessary. However, I also found issue #212, so I'm not sure if option ROM will always be reliably detected. Feel free to reject this PR if there is already a reliable warning when you have option ROM (I don't so I can't test).
I also did not include the `-m` flag by default in the `sbctl enroll-keys`, since I was not sure how widespread OpROMs are.
Some `$`s were also changed to `#`s to indicate that they should be run as root (didn't …

Add Option ROM warning to Usage section of the manpage

---

cmd/sbctl/export-enrolled-keys.go
go.mod
go.sum
tests/integration_test.go
tests/integrations/export_enrolled_keys/export_enrolled_keys_test.go

This PR introduces an `export-enrolled-keys` command that allows the user to export the already enrolled keys to a directory for backup reasons (e.g. before making any changes on new hardware) and to prepare a directory that can be used as a "custom certs" when enrolling keys.
User scenario:
- User buys some new hardware with MS and vendor keys already enrolled
- User backs up the built-in keys using this new command
- User generates new keys (intended to sign their own OSes)
- User puts the machine in "setup mode" by deleting PK, KEK and db from bios
- User enrolls the new keys including the original ones as "custom keys"
This PR is only one of the things needed to implement the above scenario. Currently the export directory structure is the one expected by the `enroll-keys` command but …

Add export-enrolled-keys command

---

contrib/kernel-install/91-sbctl.install

Unifies usage of testing commands like `[]`, `test`, and `[[]]` to just
use `[]` everywhere. This also improves compatibility, as `[[]]` is not
available in POSIX sh.
N.B.: the script uses `#!/bin/sh`, so using `[[]]` as before can cause crashes
if the system has a symlink `sh -> dash`. This could also be fixed by changing
the shebang to use `bash` instead.

nit(91-sbctl.install): consistent syntax for tests

---

contrib/kernel-install/91-sbctl.install

This partially undoes 5106d1ef8aaf72e545eb86d4a1ba0ca42996f1e4, but avoids that problem by ignoring non-zero exit statuses from `sbctl remove-file`. That commit stopped the script from failing when uninstalling a kernel where the UKI wasn't in sbctl's database. However, it causes the UKI to never be removed from the database if UKI removal is done by a script that runs before `91-sbctl.install`.
This is the case with systemd-ukify's `60-ukify.install` and systemd's `90-uki-copy.install`. By the time that `91-sbctl.install` runs during kernel removal, `90-uki-copy.install` will have already deleted the UKI.

91-sbctl.install: Unconditionally remove file from database

---

cmd/sbctl/main.go

`PersistentPreRun` was being overwritten later in `main()`, causing `logging.PrintOff()` to never be called.
EDIT: Updated with @Foxboron's suggestion below.

sbctl: Fix human readable output being printed when using `--json`

---

cmd/sbctl/list-bundles.go
cmd/sbctl/sign-all.go
cmd/sbctl/sign.go
database.go
lsm/lsm.go

Fixes: https://github.com/Foxboron/sbctl/issues/340

Ensure landlock works for signing entries

---

docs/sbctl.8.txt

The same typo is in the release notes for 0.15:
> Note that only RSA 2048 is supported by most TPMs while the default `file` type
defaults to RSA 409***8***.

sbctl.8: fix typo in the man page

---

sbctl.go
sbctl_test.go

Fixes: https://github.com/Foxboron/sbctl/issues/207

fix esp detection with multiple mountpoints and failing udev info

---

cmd/sbctl/sign.go

The mkinitcpio hook runs `sbctl sign "$IMAGE_FILE"` and has no way to know the output file path for the corresponding image file. This results in signing in place which may break booting for those who with different locations for signed and unsigned UKIs.
The sign command should check if the given file is in the database and use the saved output file path.

Read output file path from db if output not specified

---

cmd/sbctl/enroll-keys.go

Appending keys can’t break a working system.
My Thinkpad T14s Gen 3 doesn’t clear the keys when entering setup mode, but even if it does, sbctl isn’t responsible for breaking the system.
It would be good to know if there are systems that clear all keys when entering setup mode. If there are many then it’d probably be best to leave it as-is.
=> please check this :)
I could check 3 systems:
- the mentioned thinkpad t14s gen3 does support setup mode and does not clear the keys
- both an msi and a tuf gaming (asus) motherboard supports secure boot but not setup mode.

fix: allow -a/--append without force

---

quirks/fq0001.go

quirks: Add MS-7D70 as unaffected

---

contrib/pacman/ZZ-sbctl.hook

REFind is installed to /usr/share/refind/

add usr/share/**/*.efi* to paths for pacman hook

---

.github/workflows/build.yml

Just update `upload-artifact@v2` to `upload-artifact@v4` due to: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

build.yml: bump actions/upload-artifact@v4

---

.gitignore

Currently this only matches sbctl.conf.5

gitignore: add generated man pages in section 5.

---

keys.go

`Stat` doesn't return `ErrExist` error, so this line is always false. We also don't need any stats for the output file, so we can just try to open the file, and continue the comparison with the input file if there is no error opening it.

Fix input/output file comparison when signing

---

cmd/sbctl/setup.go

When running `sbctl sbctl setup --migrate`, the output if sbctl isn't installed is `sbctl is not installd`, this PR fixes the typo.

sbctl setup migrate: fix typo

---

cmd/sbctl/setup.go

`sbctl setup` exits with status code 0 and doesn't print anything. Because one argument is required (`--migrate`, `--print-config`, `--print-state` or `--setup`), `sbctl setup` without other options should be an error.

fix: print an error on setup without args
